apiserver:
    FB_APP_ID: ENC[AES256_GCM,data:9G5MzM0ODCAvGJtjNMC1,iv:9zQA3n2/NAGg0T3rXeLvIkz8Xk7PZflHXofVrv/Ugx0=,tag:I6rXIo6FoZg8lWtyIczdYg==,type:str]
    FB_APP_SECRET: ENC[AES256_GCM,data:7NQ4+KpmdOLhI+G2+owFHacV2JIb729AYDbS/LZBZ58=,iv:Y52hJThvwWXMLNK+4sACR1xpwck5orgh/Ff54CvGfII=,tag:1QPRdJPX8RWaWkYC+xHVAQ==,type:str]
    MONGO_DB_NAME: ENC[AES256_GCM,data:dA1/hzZBVzbacA==,iv:opRERYZSicLCDBRbTSTn8zMmR5L4DFS37nSFN5yeyXs=,tag:SKjAC398NZWX8ueNNd7zcQ==,type:str]
    MONGO_HOST: ENC[AES256_GCM,data:15Y/RA9GoXBxd5Dg/VTrmrRs,iv:GO+9r7gwKHwTpGVHQB7GExVr6h0+5/+1ORQiYVUmko0=,tag:3TQl/C+Ks/x5gs5aL2WpgA==,type:str]
    MONGO_PASS: ENC[AES256_GCM,data:sXREggW2YR3zkB2wR2GEZl5ZoV2JSFthgm8mCe65pXOt7iGZeoaYNDlhsB0=,iv:+1bfVq2eiBRUOMYLimwi5FTAknVH61fMeQhzigvO6Sw=,tag:ZpgzSSTVyKpJF2GmrZEbDA==,type:str]
    MONGO_USER: ENC[AES256_GCM,data:6/ca0UWo5yPWlquLgOyc,iv:/C9lIDvszg7BuNci+kulnvnkUYuyBTUALGhjuIr9WlU=,tag:/SrTmNeA53Ulind/MfUJsw==,type:str]
    TOKEN_SECRET: ENC[AES256_GCM,data:0OAZxDMyHsrAwMqPGJ5k83hwJBdET/m+4jKescgM3wqLSQlcs4qisIlvGjk=,iv:WlNEoC/h8FdGNcb+BiynGc/+DbOCvnugYTZZe3LNhYo=,tag:8WgsvFxnLsSgllXoppAHJg==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:l6c5AH6ZloShLL/Bc4Zwso3Mq7r9DO8=,iv:gzgYDE8cwD8eT8YMfN452qlQtotPU+9BmFa8C/cuoo8=,tag:YF4EFgYxMzroL5tI/C7bgA==,type:str]
    REDIS_PASS: ENC[AES256_GCM,data:Y2ccw8y/6/+1BN8g4xXT27DDfckx5iwKK9AoV8t52dJ7QEdb+R26sn0XqS4=,iv:H7EAYrULkoEXPZdBCfjK4lMIdZJogFRaaKTJqtQzog0=,tag:w9VfmLb5KM+b9U95n0sFGg==,type:str]
mongodb:
    mongodbRootPassword: ENC[AES256_GCM,data:qW2QWm1SpGVZkrpzjvb23LFyZdtsyWvhFPj3LHtiBtDmnnwsOBNrION8euE=,iv:fP2zt7NP2ZOSHhfmbrSFdHEnWezDUKaUUJYf/yjiDUE=,tag:ruy8mmpcj5o6EA4nETbPdg==,type:str]
    mongodbUsername: ENC[AES256_GCM,data:wGQRrXmK9vj5nNu8gMJt,iv:1mYNRI+gVI81mGL3ZcOVYfQQjvFWQAm2aNZZLZS9CN0=,tag:sbMIfUwsHO0eTz3r6+u9uw==,type:str]
    mongodbPassword: ENC[AES256_GCM,data:3y4tEykM1XTihto4FZuR/uwU2Sw0z2IjpKYg9KbU+DLA3FU881kckbzlbvo=,iv:S2titUd80bmi0T9GpK27FIqyFr/2a/7pgCYcNTLXKqg=,tag:ILkjPusDdPLKEeUxBaBV9Q==,type:str]
    mongodbDatabase: ENC[AES256_GCM,data:HIjI72PgLkIRmA==,iv:fvc0Jw9NToj+WXWn4M8NuHibUiogmW0N8+FHICOq188=,tag:qVFZ8THjlIquOR2qVRX6qw==,type:str]
redis:
    password: ENC[AES256_GCM,data:Oxttf/etnwUKyxYLALaRE2gbSsfMgNaTa3YuhHEGJL1uQgmnABLSh4/xgqw=,iv:d9t6X2h2eK1VkoMturOIovSJxvPpF7/6hBssWz1Bou8=,tag:BXkewc3sihbW/KzjtHi2FQ==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-west-2:173316437537:key/800b1fa9-a2a6-4f81-b895-f0e67e4534d7
        created_at: '2019-02-24T08:21:03Z'
        enc: AQICAHhCcZgz9Hdgya//Fxgh/5aftA4A6MuHy9hvq0XhIfjV1QHV8eaQfHzQYMj/8PJCRmfXAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM8VWsaGupMRTcrX5HAgEQgDuG1c0N1+J7LS/nfGQg+9Q4hpnZFknK5/UtNLv1QfI1sDpoQyGEk8hZMzkoXScpqKK2MD86JpEQUFjLwg==
    gcp_kms: []
    azure_kv: []
    lastmodified: '2019-02-25T04:18:20Z'
    mac: ENC[AES256_GCM,data:uw/5/f84a+iCuIp69RGhdukpzEL2TAeG1r/WdgBQZaPedremhQV17JO9WNaIjUEnKB7EN5NR1nyeDjO4Fz86E92PB22/I+tzvm+1hTiI9qg0NqO71vbbkiEGu2V2oa/IwUL2napfxKYHk7op0P0HrP27eqeWpDkJLbXKAzTweCk=,iv:iSTsrUNRqxsWXG4Y0SIppXmRh/l0+BN/B7B+NqxjEyw=,tag:nTqcFHxbdbZkC6JiHxaLEg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.2.0
