dependencies:
- name: mongodb
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: 5.3.4
- name: redis
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: 6.1.0
